namespace Domain.Helper
{
    public static class Mapping
    {
        public static Models.BradescoBoleto ToModel(this Infra.Entidades.BradescoBoleto boleto)
        {
            return new Models.BradescoBoleto()
            {
                agenciaDestino = boleto.agenciaDestino,
                bairroPagador = boleto.bairroPagador,
                bairroSacadorAvalista = boleto.bairroSacadorAvalista,
                cdEspecieTitulo = boleto.cdEspecieTitulo,
                cdIndCpfcnpjPagador = boleto.cdIndCpfcnpjPagador,
                cdIndCpfcnpjSacadorAvalista = boleto.cdIndCpfcnpjSacadorAvalista,
                cdPagamentoParcial = boleto.cdPagamentoParcial,
                cepPagador = boleto.cepPagador,
                cepSacadorAvalista = boleto.cepSacadorAvalista,
                codigoMoeda = boleto.codigoMoeda,
                complementoCepPagador = boleto.complementoCepPagador,
                complementoCepSacadorAvalista = boleto.complementoCepSacadorAvalista,
                complementoLogradouroPagador = boleto.complementoLogradouroPagador,
                complementoLogradouroSacadorAvalista = boleto.complementoLogradouroSacadorAvalista,
                controleParticipante = boleto.controleParticipante,
                ctrlCPFCNPJ = boleto.ctrlCPFCNPJ,
                dataLimiteDesconto1 = boleto.dataLimiteDesconto1,
                dataLimiteDesconto2 = boleto.dataLimiteDesconto2,
                dataLimiteDesconto3 = boleto.dataLimiteDesconto3,
                dddPagador = boleto.dddPagador,
                dddSacadorAvalista = boleto.dddSacadorAvalista,
                dtEmissaoTitulo = boleto.dtEmissaoTitulo,
                dtLimiteBonificacao = boleto.dtLimiteBonificacao,
                dtVencimentoTitulo = boleto.dtVencimentoTitulo,
                endEletronicoPagador = boleto.endEletronicoPagador,
                endEletronicoSacadorAvalista = boleto.endEletronicoSacadorAvalista,
                filialCPFCNPJ = boleto.filialCPFCNPJ,
                formaEmissao = boleto.formaEmissao,
                idProduto = boleto.idProduto,
                logradouroPagador = boleto.logradouroPagador,
                logradouroSacadorAvalista = boleto.logradouroSacadorAvalista,
                municipioPagador = boleto.municipioPagador,
                municipioSacadorAvalista = boleto.municipioSacadorAvalista,
                nomePagador = boleto.nomePagador,
                nomeSacadorAvalista = boleto.nomeSacadorAvalista,
                nuCPFCNPJ = boleto.nuCPFCNPJ,
                nuCliente = boleto.nuCliente,
                nuCpfcnpjPagador = boleto.nuCpfcnpjPagador,
                nuCpfcnpjSacadorAvalista = boleto.nuCpfcnpjSacadorAvalista,
                nuLogradouroPagador = boleto.nuLogradouroPagador,
                nuLogradouroSacadorAvalista = boleto.nuLogradouroSacadorAvalista,
                nuNegociacao = boleto.nuNegociacao,
                nuTitulo = boleto.nuTitulo,
                percentualBonificacao = boleto.percentualBonificacao,
                percentualDesconto1 = boleto.percentualDesconto1,
                percentualDesconto2 = boleto.percentualDesconto2,
                percentualDesconto3 = boleto.percentualDesconto3,
                percentualJuros = boleto.percentualJuros,
                percentualMulta = boleto.percentualMulta,
                prazoBonificacao = boleto.prazoBonificacao,
                prazoDecurso = boleto.prazoDecurso,
                prazoProtestoAutomaticoNegativacao = boleto.prazoProtestoAutomaticoNegativacao,
                qtdeDiasJuros = boleto.qtdeDiasJuros,
                qtdeDiasMulta = boleto.qtdeDiasMulta,
                qtdePagamentoParcial = boleto.qtdePagamentoParcial,
                quantidadeMoeda = boleto.quantidadeMoeda,
                registraTitulo = boleto.registraTitulo,
                telefonePagador = boleto.telefonePagador,
                telefoneSacadorAvalista = boleto.telefoneSacadorAvalista,
                tipoDecurso = boleto.tipoDecurso,
                tpProtestoAutomaticoNegativacao = boleto.tpProtestoAutomaticoNegativacao,
                ufPagador = boleto.ufPagador,
                ufSacadorAvalista = boleto.ufSacadorAvalista,
                versaoLayout = boleto.versaoLayout,
                vlAbatimento = boleto.vlAbatimento,
                vlBonificacao = boleto.vlBonificacao,
                vlDesconto1 = boleto.vlDesconto1,
                vlDesconto2 = boleto.vlDesconto2,
                vlDesconto3 = boleto.vlDesconto3,
                vlIOF = boleto.vlIOF,
                vlJuros = boleto.vlJuros,
                vlMulta = boleto.vlMulta,
                vlNominalTitulo = boleto.vlNominalTitulo
            };
        }
    }
}
